#!/usr/bin/env bash

# Tests the animations in ./animations

[[ -t 1 ]] || exit 1

animations_dir="$(realpath "$(dirname "${0}")/animations")"
cmd="$(realpath "$(dirname "${0}")/tan")"
echo

cd "${animations_dir}" || exit 1
for animation in *.sh; do
	animation="${animation%.sh}"
	printf "\r\e[1A\e[0J" && "${cmd}" -A . -a "${animation}" -p "${animation} " "${@}" -- sleep 5 || exit
done
